name = "laiba-rasa-app"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "laiba-prod"
database_id = "5684cf5a-9609-450a-bc7f-36386d560544"
preview_database_id = "5684cf5a-9609-450a-bc7f-36386d560544"
