-- Career Categories
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5uzz00003de8sh915ss3','ai','Yapay Zeka & YZ Uygulamaları','Artificial Intelligence & AI Applications','','Yapay zeka, makine öğrenmesi ve derin öğrenme teknolojileri','','','🤖','#00d4ff','Zeka Kalesi','AI Fortress','','Kod Büyücüsü','Code Wizard','',1,'2026-03-07T23:49:00.336Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v0b00013de8i0d7os2z','metaverse','Metaverse & Sanal Dünya','Metaverse & Virtual World','','Sanal gerçeklik, artırılmış gerçeklik ve metaverse teknolojileri','','','🌐','#a855f7','Dijital Medine','Digital Medina','','Dijital Diyar Kurucusu','Digital Realm Founder','',2,'2026-03-07T23:49:00.347Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v0i00023de8ibgmqk5v','data','Veri & Analitik','Data & Analytics','','Büyük veri, veri bilimi ve analitik','','','📊','#22c55e','Veri Kalesi','Data Fortress','','Veri Kâşifi','Data Explorer','',3,'2026-03-07T23:49:00.354Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v0n00033de8jhsuhjf0','cyber','Siber Güvenlik & Blockchain','Cybersecurity & Blockchain','','Siber güvenlik, blockchain ve kriptografi','','','🔐','#ef4444','Şifre Burcu','Cipher Bastion','','Siber Kalkan','Cyber Shield','',4,'2026-03-07T23:49:00.360Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v0t00043de86lpi3xh5','robotics','Robotik & Otonom Sistemler','Robotics & Autonomous Systems','','Robotik, dron ve otonom araç teknolojileri','','','🦾','#f97316','Mekanik Vadi','Mechanical Valley','','Makine Ustası','Machine Master','',5,'2026-03-07T23:49:00.365Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1000053de8yywvbkja','health','Sağlık & Biyoteknoloji','Health & Biotechnology','','Biyoteknoloji, genomik ve dijital sağlık','','','🧬','#14b8a6','Şifa Bahçesi','Healing Garden','','Şifa Bilgini','Healing Sage','',6,'2026-03-07T23:49:00.372Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1700063de8nhtxovqo','environment','Çevre & Sürdürülebilirlik','Environment & Sustainability','','Çevre bilimi, sürdürülebilirlik ve yeşil enerji','','','🌿','#22c55e','Yeşil Kule','Green Tower','','Yeşil Muhafız','Green Guardian','',7,'2026-03-07T23:49:00.379Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1d00073de8aipnzlzm','law','Hukuk, Etik & Regülasyon','Law, Ethics & Regulation','','Dijital hukuk, YZ etiği ve regülasyon','','','⚖️','#f5c518','Adalet Sarayı','Justice Palace','','Adalet Bekçisi','Justice Keeper','',8,'2026-03-07T23:49:00.385Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1j00083de8kuvh6dqu','marketing','Pazarlama & İletişim','Marketing & Communication','','Dijital pazarlama, içerik üretimi ve sosyal medya','','','📣','#fb7185','Ses Kalesi','Voice Fortress','','Ses Efsanesi','Voice Legend','',9,'2026-03-07T23:49:00.392Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1r00093de8hapj843l','education','Eğitim & Koçluk','Education & Coaching','','Eğitim teknolojileri, koçluk ve mentorluk','','','📚','#f59e0b','Bilgi Tapınağı','Knowledge Temple','','Bilge Mentor','Wise Mentor','',10,'2026-03-07T23:49:00.399Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v1y000a3de8bhy75p72','design','Tasarım & Yaratıcı Sanatlar','Design & Creative Arts','','UX/UI tasarım, 3D modelleme ve dijital sanat','','','🎨','#c084fc','Sanat Atölyesi','Creative Workshop','','Sanat Ustası','Art Master','',11,'2026-03-07T23:49:00.406Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v25000b3de8ftfzx9fi','finance','Finans & Ekonomi','Finance & Economy','','Fintech, kripto ekonomisi ve DeFi','','','💰','#eab308','Altın Kasa','Golden Vault','','Altın Stratejist','Golden Strategist','',12,'2026-03-07T23:49:00.413Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v2c000c3de87ksootf2','psychology','Psikoloji & Ruh Sağlığı','Psychology & Mental Health','','Psikoloji, dijital terapi ve ruh sağlığı','','','🧠','#a78bfa','Zihin Bahçesi','Mind Garden','','Zihin Okuyucu','Mind Reader','',13,'2026-03-07T23:49:00.420Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v2h000d3de8ogkephre','gaming','Oyun & E-Spor','Gaming & E-Sports','','Oyun tasarımı, e-spor ve oyun analitiği','','','🎮','#ec4899','Arena Stadyumu','Arena Stadium','','Arena Efsanesi','Arena Legend','',14,'2026-03-07T23:49:00.426Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v2n000e3de86klcfk8q','science','İleri Bilim & Uzay','Advanced Science & Space','','Kuantum, nanoteknoloji ve uzay bilimi','','','🚀','#8b5cf6','Yıldız Gözlemevi','Star Observatory','','Yıldız Kaşifi','Star Explorer','',15,'2026-03-07T23:49:00.431Z');
INSERT OR IGNORE INTO "CareerCategory" ("id","slug","nameTr","nameEn","nameAr","descriptionTr","descriptionEn","descriptionAr","icon","colorHex","worldNameTr","worldNameEn","worldImage","heroNameTr","heroNameEn","heroImage","sortOrder","createdAt") VALUES ('cmmgz5v2t000f3de8kx3bdl30','cross','Diğer / Kesişimsel Meslekler','Cross-Disciplinary Careers','','Birden fazla alanı kesen kesişimsel meslekler','','','⚡','#facc15','Kahraman Kavşağı','Hero Crossroads','','Çok Yönlü Kahraman','Multi-Path Hero','',16,'2026-03-07T23:49:00.438Z');
